FROM python:3.11

RUN useradd -m -u 1000 user
USER user
ENV PATH="/home/user/.local/bin:$PATH"

WORKDIR /app

COPY --chown=user ./requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY --chown=user . /app

# We use 8000 because that is what we opened in the Oracle VCN
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
